<?php

/**
 * @file
 * Module file. Gives the the users the ability to search for libraries
 */

/**
 * Implements hook_form_FORM_ID_alter
 * Creates a field for adding a URL for the Ting Agency Serach webservice
 */
function bibdk_vejviser_form_ting_admin_ting_settings_alter(&$form, &$form_state, $form_id) {
  $form['ting']['vejviser'] = array(
    '#type' => 'textfield',
    '#title' => 'OpenAgency URL',
    '#description' => t('URL to the Ting agencysearch webservice, e.g. http://openagency.addi.dk/1.6/'),
    '#required' => TRUE,
    '#default_value' => variable_get('ting_agency_search_url', ''),
  );
}

/**
 * Implements hook_block_info();
 */
function bibdk_vejviser_block_info() {
  $blocks['bibdk_vejviser'] = array(
    'info' => t('Bibdk Vejviser'),
    'description' => t('Search for libraries'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_configure();
 */
function bibdk_vejviser_block_view($delta = '') {
  switch ($delta) {
    case 'bibdk_vejviser':

      $block['title'] = t('Find Library');
      $block['content'] = drupal_get_form('bibdk_vejviser_form');
      return $block;
      break;
  }
}

function bibdk_vejviser_form() {
  $form = array();
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#size' => 5,
  );
  $form['zip'] = array(
    '#type' => 'textfield',
    '#title' => t('Zip'),
    '#size' => 5,
  );
  $form['city'] = array(
    '#type' => 'textfield',
    '#title' => t('City'),
    '#size' => 5,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
    '#executes_submit_callback' => TRUE,
  );
  return $form;
}

function bibdk_vejviser_form_submit($form, $form_state) {
  drupal_set_message('form submit');
}